DATA:
    Folder: images
    Name_Sets:
        A: 
            F: Linda, Peggy, Susan, Joyce, Karen, Dawn
            M: John, Henry, Ed, Gene, Sam, Bruce
        B: 
            F: Diane, Carol, Patricia, Sarah, Ruth, Beverly
            M: Steven, Harry, Thomas, Barry, George, Charles
        C: 
            F: Janet, Melanie, Laurie, Kathy, Anna, Barb
            M: Walter, Carl, Arthur, Phil, Ray, Daniel
    Name_Triplets:
        Linda: Linda, Susan, Lena 
        Peggy: Peggy, Karen, Michelle
        Susan: Susan, Joyce, Jenny
        Joyce: Joyce, Peggy, Cheryl
        Karen: Karen, Dawn, Judy
        Dawn: Dawn, Linda, Joanne
        John: John, Ed, Don
        Henry: Henry, John, Jerry
        Ed: Ed, Bruce, Tim
        Gene: Gene, Henry, Jeff
        Sam: Sam, Gene, Howard
        Bruce: Bruce, Sam, Allen
        Diane: Diane, Ruth, Donna
        Carol: Carol, Diane, Anne
        Patricia: Patricia, Sarah, Dorothy
        Sarah: Sarah, Carol, Helen
        Ruth: Ruth, Beverly, Liz
        Beverly: Beverly, Patricia, Lois
        Steven: Steven, Thomas, Brian
        Harry: Harry, George, Gerry
        Thomas: Thomas, Harry, Bob
        Barry: Barry, Steven, Neil
        George: George, Charles, Donald
        Charles: Charles, Barry, Rob
        Janet: Janet, Kathy, Jessica
        Melanie: Melanie, Janet, Dorene
        Laurie: Laurie, Melanie, Gloria
        Kathy: Kathy, Barb, Margaret
        Anna: Anna, Laurie, Christine
        Barb: Barb, Anna, Phyllis
        Walter: Walter, Ray, Roger
        Carl: Carl, Walter, greg
        Arthur: Arthur, Phil, Ronnie
        Phil: Phil, Carl, Will
        Ray: Ray, Daniel, Harry
        Daniel: Daniel, Arthur, Mark
    Image_File_Names: 
        Correct: NAME_1.jpeg
        Wrong1: NAME_2.jpeg
        Wrong2: NAME_3.jpeg
        
INSTRUCTIONS:
    Learning:
      - You will be shown a series of <Num_Of_Stimuli> face**–**name pairs. Each time, you will be shown a single face together with its name. After <Time_Per_Stimulus_Learning> seconds, the image will be replaced by a slider on which you will be asked to rate how well the name fits the face.
    Recall:
      - Now you will be presented each time with a face and three names. Your task is to select the correct name from the three. You will have <Time_Per_Stimulus_Recall> seconds for each trial and <Num_Of_Stimuli> trials overall. 
    Break:
      - Time for a short break! You'll play a word-guessing game. The computer picks a secret word. Ask questions by entering two words — the computer tells you which one is semantically closer to the secret. You can also buy a hint. You start with 20 points; each question costs 1, each wrong guess 3, each hint 5. Points run out and the answer is revealed. Good luck!
    Delayed_Recall:    
      - "Hello again! This time, you will be presented with a set of three faces and asked three questions: (1) Which of the faces have you previously seen? (<Time_IsFamiliar> seconds) (2) What is the first letter of their name? (<Time_1stLetter> seconds) (3) What is the full first name as shown in the learning phase? (<Time_FullName> seconds)."

CONFIG:
    Stimuli:
        Name_Set: A
        Num_Of_Stimuli: 8
    Learning_Phase:
        Num_Learning_Rounds: 2
        Time_Per_Stimulus_Learning: 8
        Time_Per_Stimulus_Recall: 10
    DelayedRecall_Phase:
        Num_Rounds: 2
        Time_IsFamiliar: 6
        Time_1stLetter: 6
        Time_FullName: 6
    Break_Game:
        Num_Rounds: 2
        Start_Score: 20
        Question_Cost: 1
        Hint_Cost: 5
        Wrong_Guess_Cost: 3
    Show_Stats: True
    Keyboard:
        Options: Querty, ThreeLines, OneLine
        Selected: Querty
    ShowSkipStage: True
    
PRESETS: 
    Standard: 
        Name_Set: A
        Num_Of_Stimuli: 12
        Num_Learning_Rounds: 2
        Time_Per_Stimulus_Learning: 8
        Time_Per_Stimulus_Recall: 8
        Num_DelayedRecall_Rounds: 2
        Time_IsFamiliar: 6
        Time_1stLetter: 6
        Time_FullName: 6
    advanced: 
        Name_Set: A
        Num_Of_Stimuli: 12
        Num_Learning_Rounds: 2
        Time_Per_Stimulus_Learning: 5
        Time_Per_Stimulus_Recall: 5
        Num_DelayedRecall_Rounds: 2
        Time_IsFamiliar: 6
        Time_1stLetter: 6
        Time_FullName: 6
    Shortest: 
        Name_Set: A
        Num_Of_Stimuli: 8
        Num_Learning_Rounds: 2
        Time_Per_Stimulus_Learning: 4
        Time_Per_Stimulus_Recall: 5
        Num_DelayedRecall_Rounds: 2
        Time_IsFamiliar: 6
        Time_1stLetter: 0
        Time_FullName: 6
        
        